revamped/app/main/__init__.py
from flask import Blueprint
from flask import current_app

main = Blueprint("main", __name__)
from . import views, errors


@main.app_context_processor
def global_variables():
    """
    Provides global variables that can be accessed directly within templates
    belonging to the 'main' blueprint.

    :return: Dict - A dictionary containing global variables to be injected
        into templates.
    """
    return dict(app_name=current_app.config["ORGANIZATION_NAME"])

revamped/app/main/views.py
import flask

from . import main


@main.route("/")
@main.route("/home")
@main.route("/homepage")
def index():
    return flask.render_template("main/index.html")


@main.route("/get_involved")
def get_involved():
    return flask.render_template("main/get_involved.html")


@main.route("/contact_us")
def contact_us():
    return flask.render_template("main/contact.html")


@main.route("/terms_and_conditions")
def terms_and_conditions():
    return flask.render_template("main/terms_and_conditions.html")


@main.route("/privacy_policy")
def privacy_policy():
    return flask.render_template("main/privacy_policy.html")

revamped/app/templates/main/contact.html
{% extends "base.html" %}
{% block title %}
Contact Us
{% endblock title %}

{% block page_content %}
<section class="py-16 bg-gray-100" style = "padding-right: 20px; padding-left: 20px;">
    <div class="container mx-auto text-center">
        <h2 class="text-3xl font-semibold text-gray-800 mb-8">Contact Us</h2>
        <p class="text-gray-700 max-w-lg mx-auto mb-8">We'd love to hear from you! If you have any questions, suggestions, or inquiries, please don't hesitate to get in touch with us.</p>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-12">
            <!-- Contact Form -->
            <div class="bg-white p-8 rounded-lg shadow-lg">
                <h3 class="text-xl font-semibold mb-4">Send Us a Message</h3>
                <form action="#" method="post">
                    <div class="mb-4">
                        <label for="name" class="block text-gray-700 mb-1">Your Name</label>
                        <input type="text" id="name" name="name" class="w-full p-2 border rounded-md focus:outline-none focus:border-blue-500" required>
                    </div>
                    <div class="mb-4">
                        <label for="email" class="block text-gray-700 mb-1">Your Email</label>
                        <input type="email" id="email" name="email" class="w-full p-2 border rounded-md focus:outline-none focus:border-blue-500" required>
                    </div>
                    <div class="mb-4">
                        <label for="message" class="block text-gray-700 mb-1">Message</label>
                        <textarea id="message" name="message" class="w-full p-2 border rounded-md h-32 resize-none focus:outline-none focus:border-blue-500" required></textarea>
                    </div>
                    <button type="submit" class="bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-500 transition duration-300">Send Message</button>
                </form>
            </div>
            <!-- Contact Information -->
            <div class="bg-white p-8 rounded-lg shadow-lg">
                <h3 class="text-xl font-semibold mb-4">Contact Information</h3>
                <p class="text-gray-700">Feel free to contact us using the following details:</p>
                <ul class="mt-4 text-gray-700">
                    <li>Email: <a href="mailto:ripoti.wapendataka@gmail.com" class="text-blue-600 hover:underline">ripoti.wapendataka@gmail.com</a></li>
                    <li>Phone: <a href="tel:+254114742348" class="text-blue-600 hover:underline">+254 114 742 348</a></li>
                    <li>Address: Ole Sang'ale Road Madaraka, Nairobi West, Kenya</li>
                </ul>
                <p class="mt-6 text-gray-700">You can also connect with us on our social media channels:</p>
                <div class="mt-4 flex justify-center space-x-4">
                    <a href="https://www.facebook.com/profile.php?id=61550937457139" target = "_blank" class="text-gray-700 hover:text-instagram transition duration-300" title="Facebook"><i class="fab fa-facebook-square fa-3x"></i></a>
                    <a href="https://twitter.com/RipotiTaka" target = "_blank" class="text-gray-700 hover:text-twitter transition duration-300" title="Twitter"><i class="fab fa-twitter-square fa-3x"></i></a>
                    <a href="https://www.linkedin.com/showcase/ripoti-taka-program" class="text-gray-700 hover:text-red-400 transition duration-300" title="Linked In"><i class="fab fa-linked-in-square fa-3x"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock page_content %}

revamped/app/templates/main/get_involved.html
{% extends "base.html" %}
{% block title %}
Get Involved
{% endblock title %}

{% block page_content %}
<!-- Get Involved Page -->
<section class="py-16 bg-gray-100">
	<div class="container mx-auto text-center">
		<h2 class="text-3xl font-semibold text-gray-800 mb-8">Get Involved</h2>
		<p class="text-gray-700 max-w-lg mx-auto mb-8">We believe that change starts with individuals coming together. Join our movement and make a positive impact on our environment and community.</p>
		<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-12">
			<!-- Volunteer -->
			<div class="bg-white p-8 rounded-lg shadow-lg text-center">
				<i class="fas fa-hands-helping text-blue-600 text-4xl mb-4"></i>
				<h3 class="text-xl font-semibold mb-4">Volunteer</h3>
				<p class="text-gray-700 mb-6">Join our dedicated team of volunteers working on various projects and initiatives. Contribute your time and skills to create a cleaner and healthier environment.</p>
				<a href="#" class="inline-block bg-blue-600 text-white py-2 px-6 rounded-md hover:bg-blue-500 transition duration-300">Sign Up to Volunteer</a>
			</div>
			<!-- Donate -->
			<div class="bg-white p-8 rounded-lg shadow-lg text-center">
				<i class="fas fa-donate text-green-600 text-4xl mb-4"></i>
				<h3 class="text-xl font-semibold mb-4">Donate</h3>
				<p class="text-gray-700 mb-6">Support our cause financially and help us sustain our projects and programs. Every donation makes a significant impact on our mission to create a sustainable future.</p>
				<a href="#" class="inline-block bg-blue-600 text-white py-2 px-6 rounded-md hover:bg-blue-500 transition duration-300">Donate Now</a>
			</div>
			<!-- Spread the Word -->
			<div class="bg-white p-8 rounded-lg shadow-lg text-center">
				<i class="fas fa-share-alt text-purple-600 text-4xl mb-4"></i>
				<h3 class="text-xl font-semibold mb-4">Spread the Word</h3>
				<p class="text-gray-700 mb-6">Help us raise awareness by sharing our mission and initiatives on social media platforms. Your support in spreading the word can inspire others to join our cause.</p>
				<a href="#" class="inline-block bg-blue-600 text-white py-2 px-6 rounded-md hover:bg-blue-500 transition duration-300">Share Now</a>
			</div>
			<!-- Attend Events -->
			<div class="bg-white p-8 rounded-lg shadow-lg text-center">
				<i class="fas fa-calendar-alt text-orange-600 text-4xl mb-4"></i>
				<h3 class="text-xl font-semibold mb-4">Attend Events</h3>
				<p class="text-gray-700 mb-6">Participate in our events, workshops, and seminars focused on sustainability and waste management. Engage with experts, learn, and connect with like-minded individuals.</p>
				<a href="#" class="inline-block bg-blue-600 text-white py-2 px-6 rounded-md hover:bg-blue-500 transition duration-300">View Events</a>
			</div>
			<!-- Educational Programs -->
			<div class="bg-white p-8 rounded-lg shadow-lg text-center">
				<i class="fas fa-book-open text-red-600 text-4xl mb-4"></i>
				<h3 class="text-xl font-semibold mb-4">Educational Programs</h3>
				<p class="text-gray-700 mb-6">Join our educational programs aimed at creating awareness about waste management and environmental sustainability among schools and communities.</p>
				<a href="#" class="inline-block bg-blue-600 text-white py-2 px-6 rounded-md hover:bg-blue-500 transition duration-300">Learn More</a>
			</div>
			<!-- Collaborate with Us -->
			<div class="bg-white p-8 rounded-lg shadow-lg text-center">
				<i class="fas fa-puzzle-piece text-indigo-600 text-4xl mb-4"></i>
				<h3 class="text-xl font-semibold mb-4">Collaborate with Us</h3>
				<p class="text-gray-700 mb-6">Are you an organization, institution, or business with a shared vision for a cleaner environment? Let's collaborate and amplify our impact together.</p>
				<a href="#" class="inline-block bg-blue-600 text-white py-2 px-6 rounded-md hover:bg-blue-500 transition duration-300">Contact Us</a>
			</div>
			<!-- Advocacy -->
			<div class="bg-white p-8 rounded-lg shadow-lg text-center">
				<i class="fas fa-bullhorn text-yellow-600 text-4xl mb-4"></i>
				<h3 class="text-xl font-semibold mb-4">Advocacy</h3>
				<p class="text-gray-700 mb-6">Be a voice for positive change by advocating for sustainable waste management policies and practices at local and national levels.</p>
				<a href="#" class="inline-block bg-blue-600 text-white py-2 px-6 rounded-md hover:bg-blue-500 transition duration-300">Join Advocacy</a>
			</div>
			<!-- Eco-friendly Practices -->
			<div class="bg-white p-8 rounded-lg shadow-lg text-center">
				<i class="fas fa-leaf text-green-600 text-4xl mb-4"></i>
				<h3 class="text-xl font-semibold mb-4">Eco-friendly Practices</h3>
				<p class="text-gray-700 mb-6">Make a difference in your daily life by adopting eco-friendly practices. Reduce, reuse, and recycle to contribute to a greener future.</p>
				<a href="#" class="inline-block bg-blue-600 text-white py-2 px-6 rounded-md hover:bg-blue-500 transition duration-300">Learn More</a>
			</div>
		</div>
	</div>
</section>
{% endblock page_content %}

revamped/app/templates/main/index.html
{% extends "base.html" %}
{% block title %}
Welcome
{% endblock title %}

{% block page_content %}
<!-- Hero Section -->
<section class="bg-blue-700 text-white py-20">
	<div class="container mx-auto text-center">
		<h1 class="text-4xl md:text-6xl font-bold mb-4">Join the Ripoti Taka Program</h1>
		<p class="text-lg md:text-xl mb-8">Empowering Kenyans to create a cleaner and greener future through sustainable waste management.</p>
		<a href="{{ url_for('registration.user_registration') }}" class="bg-yellow-500 hover:bg-yellow-400 text-blue-800 hover:text-blue-700 py-2 px-6 rounded-full text-lg font-semibold transition duration-300">Get Started</a>
	</div>
</section>

<!-- About Us Section -->
<section class="py-16" style = "padding-right: 20px; padding-left: 20px; padding-bottom:0;">
	<div class="container mx-auto text-center">
		<h2 class="text-3xl font-semibold mb-6">About Mazingira Yetu Initiative</h2>
		<p class="text-lg text-gray-700 mb-8">Mazingira Yetu Initiative is a Kenyan non-profit organization dedicated to promoting sustainable waste management practices. Our vision is to transform Kenya into a model of environmental responsibility and cleanliness within a decade.</p>
		<p class="text-lg text-gray-700 mb-8">Through community engagement, innovative technology, and collaboration, we aim to eliminate waste-related pollution and create a healthier environment for all Kenyans.</p>
	</div>
</section>

<!-- Ripoti Taka Program -->
<section class="bg-gray-100 py-16" style = "padding-top: 10px;">
	<div class="container mx-auto text-center">
		<h2 class="text-3xl font-semibold mb-6">Ripoti Taka Program</h2>
		<p class="text-lg text-gray-700 mb-8">Our flagship Ripoti Taka Program empowers individuals to report and address waste-related issues. By utilizing modern technology, gamification, and community involvement, we're revolutionizing waste management.</p>
		<a href="{{ url_for('main.get_involved') }}" class="bg-blue-600 hover:bg-blue-500 text-white py-3 px-8 rounded-full text-lg font-semibold transition duration-300">Learn More</a>
	</div>
</section>

<!-- How Ripoti Program Works -->
<section class="py-16 bg-white">
	<div class="container mx-auto text-center">
		<h2 class="text-3xl font-semibold mb-6">How the Ripoti Taka Program Works</h2>
		<div class="grid grid-cols-1 md:grid-cols-2 gap-12">
			<div>
				<img src="{{ url_for('static', filename = 'img/trash.jpg') }}" alt="Ripoti Taka Program - How it Works" class="mx-auto h-64 md:h-auto md:max-h-80">
			</div>
			<div class="md:text-left">
				<p class="text-lg text-gray-700 mb-4">Our Ripoti Taka Program operates through a simple process:</p>
				<ol class="list-decimal list-inside">
					<li class="mb-2">Citizens report waste-related issues using our user-friendly web or mobile app.</li>
					<li class="mb-2">Our team receives the reports and coordinates responses with stakeholders.</li>
					<li class="mb-2">Real-time updates are provided to users as issues are resolved.</li>
					<li class="mb-2">Engage with the community through gamification and rewards.</li>
				</ol>
			</div>
		</div>
	</div>
</section>

<!-- Program Features -->
<section class="py-16 bg-gray-100">
	<div class="container mx-auto text-center">
		<h2 class="text-3xl font-semibold mb-8">Key Program Features</h2>
		<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
			<!-- Feature 1 -->
			<div class="p-4 bg-white rounded-lg shadow-md flex flex-col justify-center items-center">
				<img src="{{ url_for('static', filename = 'img/efficient-reporting-home.gif') }}" alt="Feature Image" class="h-32 w-full object-cover mb-4 rounded-t-lg">
				<h3 class="text-xl font-semibold mb-3">Effortless Reporting</h3>
				<p class="text-gray-700">Report waste issues using your device's geolocation for pinpoint accuracy.</p>
			</div>
			<!-- Feature 2 -->
			<div class="p-4 bg-white rounded-lg shadow-md flex flex-col justify-center items-center">
				<img src="{{ url_for('static', filename = 'img/real-time-update-home.gif') }}" alt="Feature Image" class="h-32 w-full object-cover mb-4 rounded-t-lg">
				<h3 class="text-xl font-semibold mb-3">Real-time Updates</h3>
				<p class="text-gray-700">Receive instant notifications and updates on the progress of your reports.</p>
			</div>
			<!-- Feature 3 -->
			<div class="p-4 bg-white rounded-lg shadow-md flex flex-col justify-center items-center">
				<img src="{{ url_for('static', filename = 'img/reward-home.gif') }}" alt="Feature Image" class="h-32 w-full object-cover mb-4 rounded-t-lg">
				<h3 class="text-xl font-semibold mb-3">Community Rewards</h3>
				<p class="text-gray-700">Engage with the community, earn points, and redeem exciting rewards.</p>
			</div>
			<!-- Feature 4 -->
			<div class="p-4 bg-white rounded-lg shadow-md flex flex-col justify-center items-center">
				<img src="{{ url_for('static', filename = 'img/data-driven-home.avif') }}" alt="Feature Image" class="h-32 w-full object-cover mb-4 rounded-t-lg">
				<h3 class="text-xl font-semibold mb-3">Data-driven Insights</h3>
				<p class="text-gray-700">Access analytics to track the impact of your contributions and the program's success.</p>
			</div>
			<!-- Feature 5 -->
			<div class="p-4 bg-white rounded-lg shadow-md flex flex-col justify-center items-center">
				<img src="{{ url_for('static', filename = 'img/community-engagement-home.jpg') }}" alt="Feature Image" class="h-32 w-full object-cover mb-4 rounded-t-lg">
				<h3 class="text-xl font-semibold mb-3">Community Engagement</h3>
				<p class="text-gray-700">Connect with fellow participants, attend events, and collaborate for a cleaner Kenya.</p>
			</div>
			<!-- Feature 6 -->
			<div class="p-4 bg-white rounded-lg shadow-md flex flex-col justify-center items-center">
				<img src="{{ url_for('static', filename = 'img/sustainable-home.png') }}" alt="Feature Image" class="h-32 w-full object-cover mb-4 rounded-t-lg">
				<h3 class="text-xl font-semibold mb-3">Sustainable Impact</h3>
				<p class="text-gray-700">Contribute to long-term environmental sustainability and improved waste management practices.</p>
			</div>
		</div>
	</div>
</section>

<!-- Benefits of the Program -->
<section class="py-16 bg-white" style = "padding-right: 20px; padding-left: 20px;">
	<div class="container mx-auto text-center">
		<h2 class="text-3xl font-semibold text-gray-800 mb-8">Benefits of Joining the Program</h2>
		<div class="grid grid-cols-1 md:grid-cols-2 gap-12">
			<!-- Benefit 1 -->
			<div class="bg-blue-200 p-8 rounded-lg">
				<h3 class="text-xl font-semibold text-blue-600 mb-3">Contribute to a Cleaner Environment</h3>
				<p class="text-gray-700">By participating, you play a crucial role in maintaining a cleaner and healthier environment for current and future generations.</p>
			</div>
			<!-- Benefit 2 -->
			<div class="bg-blue-200 p-8 rounded-lg">
				<h3 class="text-xl font-semibold text-blue-600 mb-3">Community Impact and Recognition</h3>
				<p class="text-gray-700">Your efforts will be recognized and celebrated within the community, fostering a sense of pride and accomplishment.</p>
			</div>
			<!-- Benefit 3 -->
			<div class="bg-blue-200 p-8 rounded-lg">
				<h3 class="text-xl font-semibold text-blue-600 mb-3">Earn Rewards and Incentives</h3>
				<p class="text-gray-700">Participate in our rewarding system where your contributions lead to exciting incentives, motivating you to make a difference.</p>
			</div>
			<!-- Benefit 4 -->
			<div class="bg-blue-200 p-8 rounded-lg">
				<h3 class="text-xl font-semibold text-blue-600 mb-3">Collaborative Community Engagement</h3>
				<p class="text-gray-700">Connect with like-minded individuals, attend events, and collaborate on projects that drive positive change in our society.</p>
			</div>
		</div>
	</div>
</section>


<!-- Call to Action -->
<section class="bg-blue-800 text-white py-16">
	<div class="container mx-auto text-center">
		<h2 class="text-3xl font-semibold mb-4">Join Us in Building a Sustainable Future!</h2>
		<p class="text-lg text-gray-300 mb-8">Together, we can make a lasting impact on Kenya's environment and create a legacy of cleanliness and well-being for generations to come.</p>
		<a href="{{ url_for('authentication.user_login') }}" class="bg-yellow-500 hover:bg-yellow-400 text-blue-800 hover:text-blue-700 py-3 px-8 rounded-full text-lg font-semibold transition duration-300">Get Involved</a>
	</div>
</section>
{% endblock page_content %}

revamped/app/templates/main/terms_and_conditions.html
{% extends "base.html" %}
{% block title %}
Terms and Conditions of Service
{% endblock title %}

{% block page_content %}
{% endblock page_content %}