revamped/app/models/handler.py
import os
import logging
from datetime import datetime


import flask
import flask_login
from flask import url_for
from werkzeug.security import generate_password_hash
from werkzeug.security import check_password_hash
from sqlalchemy.ext.hybrid import hybrid_property
from itsdangerous.url_safe import URLSafeTimedSerializer as Serializer


from .role import Role
from .permission import Permission
from app import db
from app import login_manager
from utilities.file_saver import save_image
from utilities.file_saver import is_allowed_file
from utilities.securities import get_gravatar_hash
from utilities.email import send_email


class AnonymousHandler(flask_login.AnonymousUserMixin):
    def can(self, permission):
        """Ensures anonymous handler can never do action on the system"""
        return False

    def is_administrator(self):
        """
        Ensures anonymous handler can never perform an administrative action
        """
        return False


login_manager.anonymous_user = AnonymousHandler


class Handler(flask_login.UserMixin, db.Model):
    """
    Model representing a handler.
    """

    __tablename__ = "handler"

    handlerId = db.Column(db.Integer, autoincrement=True, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    handlerType = db.Column(db.String(255), nullable=False)
    passwordHash = db.Column(db.String(255))
    resourceAvailability = db.Column(db.Text)
    emailAddress = db.Column(db.String(255), nullable=False, unique=True)
    avatarHash = db.Column(db.String(255))
    phoneNumber = db.Column(db.String(255), nullable=False)
    isConfirmed = db.Column(db.Boolean, default=False)
    isApproved = db.Column(db.Boolean, default=False)
    dateCreated = db.Column(db.DateTime, default=datetime.utcnow)
    lastUpdated = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )
    imageUrl = db.Column(db.String(255))

    reportAssignments = db.relationship(
        "ReportAssignment",
        back_populates="handler",
        cascade="all, delete-orphan",
    )

    def __repr__(self):
        return (
            f"Handler(handlerId={self.handlerId}, name='{self.name}', "
            + f"isApproved={self.isApproved})"
        )

    @classmethod
    def registerAccount(cls, details={}):
        """
        Create a new handler.
        """
        handler = Handler(
            name=details.get("name"),
            handlerType=details.get("handlerType"),
            resourceAvailability=details.get("resourceAvailability"),
            emailAddress=details.get("emailAddress"),
            phoneNumber=details.get("phoneNumber"),
            imageUrl=details.get("imageUrl"),
            password=details.get("password"),
        )
        db.session.add(handler)
        db.session.commit()
        return handler

    def delete(self):
        """
        Delete the handler.
        """
        db.session.delete(self)
        db.session.commit()

    def updateDetails(self, details={}):
        """
        Update the details of the handler.
        """
        self.name = details.get("name", self.name)
        self.handlerType = details.get("handlerType", self.handlerType)
        self.resourceAvailability = details.get(
            "resourceAvailability", self.resourceAvailability
        )
        self.emailAddress = details.get("emailAddress", self.emailAddress)
        self.phoneNumber = details.get("phoneNumber", self.phoneNumber)
        self.imageUrl = details.get("imageUrl", self.imageUrl)

        db.session.commit()
        return self

    def get_id(self):
        """
        Inherited HandlerMixin class method used to retrieve handler id for
            Flask-Login
        """
        return self.handlerId

    def login(self, details={}):
        """
        Authenticates the handler and logs them in when provided passsword is
            valid.

        :param details: dict - Contains password and remember_me boolean
            variable

        :return: tuple - Contains the return status and return message.
        """
        # Set handler type session variable
        flask.session.permanent = True
        flask.session["user_type"] = "handler"

        if self.verifyPassword(details.get("password", "")):
            flask_login.login_user(self, details.get("remember_me", False))
            return (1, "Login Successful")

        return (0, "Invalid password")

    def logout(self):
        """
        Terminate active handler session.

        :return: tuple - Contains return status and return message.
        """
        flask_login.logout_user()
        return (1, "Logout successful")

    def verifyPassword(self, password):
        """
        Verify whether the provided password matches the hashed password.

        :param password: str - The password to be verified.

        :return: bool - True if the password is verified, False otherwise
        """
        return check_password_hash(self.passwordHash, password)

    @property
    def password(self):
        """
        Raise an AttributeError since the password is private only
        """
        raise AttributeError("password is not a readable attribute")

    def getOnline(self):
        """
        Update the handler's last seen timestamp.

        :return: None
        """
        self.lastSeen = None
        db.session.commit()

    def getOffline(self):
        """
        Update the handler's last seen timestamp.

        :return: None
        """
        self.lastSeen = datetime.utcnow()
        db.session.commit()

    @hybrid_property
    def isOnline(self):
        """
        Check whether handler is online.

        :return: bool - True if handler is online, False otherwise.
        """
        if not self.lastSeen:
            return False

        return True

    @password.setter
    def password(self, password):
        """
        Hash the client's password
        """
        self.passwordHash = generate_password_hash(password)

    def updateProfileImage(self, image, folder):
        """
        Update handler's profile image.

        :param image: FileStorage - the image file to be uploaded.
        :param folder: str - the folder in which the image will be stored.

        :return self: Handler - the updated Handler instance.
        """
        if not is_allowed_file(image):
            return (40, "Invalid Image")

        # Delete current image file from the file system
        if self.imageUrl:
            file_path = os.path.join(folder, self.imageUrl)
            os.remove(file_path)

        # Save image on file system
        saved_filename = save_image(image, folder)

        # Save filename in database
        self.imageUrl = saved_filename
        db.session.add(self)
        db.session.commit()

        return self

    def deleteProfileImage(self, folder):
        """
        Deletes handler's profile image.

        :param folder: str - the folder in which the image will be stored.
        """
        # Delete actual file from the file system
        file_path = os.path.join(folder, self.imageUrl)
        os.remove(file_path)

        # Update the same on the database
        self.imageUrl = None
        db.session.add(self)
        db.session.commit()

    def getGravatar(self, size=100, default="identicon", rating="g"):
        """
        Generate a Gravatar Url for the handler.

        This method generates a Gravatar Url for the handler based on
            their email address.

        :param size: int - The size of the Gravatar image.
        :param default: str - The default image to be displayed if no
            Gravatar is found.
        :param rating: str - The content rating for the image.

        :return: str - The Gravatar Url.
        """
        url = "https://secure.gravatar.com/avatar"

        # Generate avatar hash if it does not exist
        if not self.avatarHash:
            self.avatarHash = get_gravatar_hash(self.emailAddress)

        # Retrieve it for usage
        hash = self.avatarHash
        return "{url}/{hash}?s={size}&d={default}&r={rating}".format(
            url=url, hash=hash, size=size, default=default, rating=rating
        )

    def can(self, permission):
        """
        Check whether a handler has a specific permission.

        :param permission: str - the permission to be checked.

        :return: bool - True if the handler has the specified permission,
            False otherwise.
        """
        role = Role.query.get(self.roleId)
        return role is not None and role.hasPermission(permission)

    def isAdministrator(self):
        """
        Check if the handler has administrator privileges.

        :return: bool - True if the handler has administrator privileges,
            False otherwise.
        """
        return self.can(Permission.ADMIN)

    def acceptHandling(self, report=None):
        """ """
        from .report_assignment import ReportAssignment

        details = {
            "reportId": report.reportId,
            "handlerId": self.handlerId,
        }
        report_assignment = ReportAssignment.create(details)

        report.status = "Assigned"
        db.session.add(report)
        db.session.commit()

        return report_assignment

    def registerSkill(self, details={}):
        """
        Registers a new skill.

        :param details: dict - Contains details used to instantiate
            the Skill object.

        :return skill: Skill - The newly created Skill instance.
        """
        # Check whether handler had the required permission
        ################################################
        #                UNDER CONSTRUCTION            #
        ################################################
        from .expert_details import Skill

        # Register new skill
        skill = Skill.register(details)
        return skill

    def registerSubject(self, details={}):
        """

revamped/app/handlers/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField
from wtforms import SelectField
from wtforms import SubmitField
from wtforms import DateField

from wtforms.validators import DataRequired


class ReportResolutionForm(FlaskForm):
    severityLevel = SelectField(
        "Severity Level",
        choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High")],
        validators=[DataRequired()],
    )
    initialSituationDescription = TextAreaField(
        "Initial Situation Description", validators=[DataRequired()]
    )
    stepsTaken = TextAreaField("Steps Taken", validators=[DataRequired()])
    recommendations = TextAreaField(
        "Recommendations", validators=[DataRequired()]
    )
    potentialCauses = TextAreaField(
        "Potential Causes", validators=[DataRequired()]
    )
    manPowerDetails = TextAreaField(
        "Manpower Details", validators=[DataRequired()]
    )
    financialCosts = TextAreaField(
        "Financial Costs", validators=[DataRequired()]
    )
    dateCompleted = DateField(
        "Date Completed",
    )
    submit = SubmitField("Submit")


class AssignReportResolutionForm(FlaskForm):
    reportResolutionId = SelectField(
        "Select resolution instance", validators=[DataRequired()],
    )
    submit = SubmitField("Create Report")

revamped/app/handlers/__init__.py
from flask import Blueprint, current_app

handlers = Blueprint("handlers", __name__, url_prefix="/handlers")
from . import views, errors


@handlers.app_context_processor
def global_variables():
    """
    Provides global variables that can be accessed directly within templates
    belonging to the 'handlers' blueprint.

    :return: Dict - A dictionary containing global variables to be injected
        into templates.
    """
    return dict(app_name=current_app.config["ORGANIZATION_NAME"])

revamped/app/handlers/views.py
import flask
from flask_login import current_user
from flask_login import login_required

from . import handlers

from .forms import ReportResolutionForm
from .forms import AssignReportResolutionForm

from app import db
from ..models import Report
from ..models import ReportResolution

from utilities.authentication import user_type_validator


@handlers.route("/dashboard")
@login_required
@user_type_validator("handler")
def dashboard():
    reports = Report.query.order_by(Report.reportId.desc()).all()
    return flask.render_template("handlers/dashboard.html", reports=reports)


@handlers.route("/add-report-resolution", methods=["GET", "POST"])
@login_required
@user_type_validator("handler")
def report_resolution():
    form = ReportResolutionForm()

    if flask.request.method == "POST":
        # Create a new Report object
        details = {
            "userId": current_user.handlerId,
            "severityLevel": form.severityLevel.data,
            "initialSituationDescription": form.initialSituationDescription.data,
            "stepsTaken": form.stepsTaken.data,
            "recommendations": form.recommendations.data,
            "potentialCauses": form.potentialCauses.data,
            "manPowerDetails": form.manPowerDetails.data,
            "financialCosts": form.financialCosts.data,
            "dateCompleted": form.dateCompleted.data,
            "status": "Completed",
        }
        ReportResolution.create(details)

        flask.flash("Resolution submitted successfully!", "success")
        return flask.redirect(flask.url_for("handlers.dashboard"))

    return flask.render_template("handlers/report_resolution.html", form=form)


@handlers.route("/reports/<int:report_id>", methods=["GET", "POST"])
@login_required
@user_type_validator("handler")
def report_details(report_id):
    report = Report.query.filter_by(reportId=report_id).first_or_404()
    form = AssignReportResolutionForm()

    form.reportResolutionId.choices = [
        (resolution.reportResolutionId, resolution.reportResolutionId)
        for resolution in ReportResolution.query.all()
    ]

    if flask.request.method == "POST":
        report_assignment = report.reportAssignments[-1]
        report_assignment.reportResolutionId = form.reportResolutionId.data
        report.status = "Resolved"

        db.session.add(report)
        db.session.add(report_assignment)
        db.session.commit()

        flask.flash("Report marked as resolved successfully", "success")
        return flask.redirect(
            flask.url_for("handlers.report_details", report_id=report_id)
            + "#comments"
        )

    return flask.render_template(
        "handlers/report_details.html",
        report=report,
        form=form,
    )


@handlers.route("/reports/my-reports", methods=["GET", "POST"])
@login_required
@user_type_validator("handler")
def my_reports():
    return flask.render_template("handlers/my_reports.html")


@handlers.route("/reports/latest-reports", methods=["GET"])
@login_required
@user_type_validator("handler")
def latest_reports():
    reports = Report.query.limit(50)
    return flask.render_template(
        "handlers/latest_reports.html", reports=reports
    )


@handlers.route("/reports/<int:report_id>/handle", methods=["GET"])
@login_required
@user_type_validator("handler")
def handle_report(report_id):
    report = Report.query.filter_by(reportId=report_id).first_or_404()
    current_user.acceptHandling(report)
    flask.flash("Report assigned to you successfully", "success")
    return flask.redirect(
        flask.url_for("handlers.report_details", report_id=report.reportId)
    )

revamped/app/templates/handlers/dashboard.html
{% extends "handlers/user_dashboard_base.html" %}

{% block title %}
Dashboard
{% endblock title %}

{% block scripts %}
{{ super() }}
{% endblock scripts %}

{%block content %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
<style>
#map {
  width: 100%;
  height: 500px;
}
</style>
<div class="flex justify-center items-center min-h-screen">
  <div class="w-full md:w-2/3">
    <!-- Report mapping -->
    <h2 class="my-6 text-2xl font-semibold text-gray-600 dark:text-gray-300">Report Mapping</h2>
    <div id="map-container" class="mb-4">
      <div id="map"></div>
    </div>
    <!-- Reports -->
    <h2 class="my-6 text-2xl font-semibold text-gray-600 dark:text-gray-300">Reports</h2>
    <div class="w-full mb-8 overflow-hidden">
      <div class="w-full overflow-x-auto">
        <table id="reportsTable" class="w-full">
          <thead>
            <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
              <th class="px-4 py-3">Location</th>
              <th class="px-4 py-3">Waste Type</th>
              <th class="px-4 py-3">Severity Level</th>
              <th class="px-4 py-3">Period of Occurence</th>
              <th class="px-4 py-3">Status</th>
              <th class="px-4 py-3">Reported On</th>
              <th class="px-4 py-3">Action</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
            {% for report in reports[:10] %}
            <tr class="text-gray-700 dark:text-gray-400">
              <td class="px-4 py-3">
                <div class="flex items-center">
                  <div class="ml-2">
                    <a href="{{ url_for('handlers.report_details', report_id=report.reportId) }}" class="text-blue-500 hover:underline">
                      {{ report.locationAddress }}
                    </a>
                  </div>
                </div>
              </td>
              <td class="px-4 py-3">
                <div class="flex items-center">
                  <div class="ml-2">
                    {{ report.wasteType }}
                  </div>
                </div>
              </td>
              <td class="px-4 py-3">
                <div class="flex items-center">
                  <div class="ml-2">
                    {{ report.severityLevel }}
                  </div>
                </div>
              </td>
              <td class="px-4 py-3">
                <div class="flex items-center">
                  <div class="ml-2">
                    {{ report.periodOfOccurence }}
                  </div>
                </div>
              </td>
              <td class="px-4 py-3">
                <div class="flex items-center">
                  <div class="ml-2">
                    {{ report.status }}
                  </div>
                </div>
              </td>
              <td class="px-4 py-3">
                <div class="flex items-center">
                  <div class="ml-2">
                    {{ moment(report.dateCreated).format('LLLL') }}
                  </div>
                </div>
              </td>
              <td class="px-4 py-3">
                <div class="flex items-center">
                  <div class="ml-2">
                    <a href="{{ url_for('handlers.report_details', report_id=report.reportId) }}" class="text-blue-500 hover:underline">
                      View
                    </a>
                  </div>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <style>
table#w-full th, table#w-full td {
  word-wrap: break-word;
  white-space: normal;
}
    </style>

  </div>
</div>
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<script>
  const kenyaCenter = { lat: -1.2921, lng: 36.8219 };
  const map = L.map('map').setView([kenyaCenter.lat, kenyaCenter.lng], 7);
  const kenyaBounds = [
      [4.831, 36.909],
      [-4.963, 40.899]
    ];
  map.fitBounds(kenyaBounds);

  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

  {% for report in reports %}
  {% if report.latitude and report.longitude %}
  L.marker([{{ report.latitude }}, {{ report.longitude }}]).addTo(map)
    .bindPopup('<div class="text-center"> <a href="{{ url_for('handlers.report_details', report_id=report.reportId) }}" class="text-blue-500 hover:underline text-lg"></a><div class="mt-4"><p style = "color:red;">{{ report.locationAddress }}</p><img src="{{ url_for('static', filename = 'images/reports/' + report.reportId | string + '/' + report.reportId | string + '_1.jpg') }}" alt="Report Image" class="w-32 h-auto mx-auto rounded-lg shadow-md"></div></div>');
  {% endif %}
  {% endfor %}
</script>
{% endblock content %}

revamped/app/templates/handlers/report_details.html
{% extends "handlers/user_dashboard_base.html" %}

{% block title %}
Report Details
{% endblock title %}

{% block content %}
{{ moment.include_moment() }}
<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<div class="container mx-auto mt-8 p-8 relative">
  <!-- Report Details Header -->
  <header class="bg-gradient-to-r from-green-500 to-green-500 rounded-lg p-6 text-white mb-8">
    <h1 class="text-4xl font-semibold mb-2">Report Details</h1>
    <p class="text-gray-200">View all the information about this report.</p>
  </header>

  {% if not report.reportAssignments %}
  <a href = "{{ url_for('handlers.handle_report', report_id=report.reportId) }}" class="mb-4 flex items-center justify-between w-full px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-indigo-600 border border-transparent rounded-lg active:bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:shadow-outline-indigo" >
    Handle current report
  </a>
    {% endif %}

    <!-- Report Card -->
    <div class="bg-gradient-to-r from-gray-400 to-gray-500 rounded-lg p-6 text-white mb-8">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <h2 class="text-2xl font-semibold mb-2">Report Information</h2>
          <p class="text-gray-200"><strong>Report ID:</strong> {{ report.reportId }}</p>
          <p class="text-gray-200"><strong>Date Reported:</strong> {{ moment(report.dateCreated).format('LLLL') }}</p>
          <p class="text-gray-200"><strong>Location:</strong> {{ report.locationAddress }}</p>
          <p class="text-gray-200"><strong>Latitude:</strong> {{ report.latitude }}</p>
          <p class="text-gray-200"><strong>Longitude:</strong> {{ report.longitude }}</p>
          <p class="text-gray-200"><strong>Waste Type:</strong> {{ report.wasteType }}</p>
          <p class="text-gray-200"><strong>Severity Level:</strong> {{ report.reportResolutionId }}</p>
          <p class="text-gray-200"><strong>Period of Occurrence:</strong> {{ report.periodOfOccurrence }}</p>
          <p class="text-gray-200"><strong>Status:</strong> {{ report.status }}</p>
          {% for assignment in report.reportAssignments %}
          <p class="text-gray-200"><strong>Assigned to:</strong> {{ assignment.handler.name }}</p>
          {% endfor %}
        </div>
        <div>
          <h2 class="text-2xl font-semibold mb-2">Report Description</h2>
          <p class="text-gray-200">{{ report.description }}</p>
        </div>
      </div>
    </div>

    <!-- User Details -->
    <div class="bg-gradient-to-r from-green-400 to-green-500 rounded-lg p-6 text-white mb-8">
      <h2 class="text-2xl font-semibold mb-4">Reported by</h2>
      <div class="flex items-center">
        {% if report.user.imageUrl %}
        <img src="{{ url_for('static', filename = 'images/handlers/' + report.user.imageUrl) }}" alt="User Image" class="w-20 h-20 rounded-full mr-4 shadow-lg">
        {% else %}
        <img src="{{ report.user.getGravatar(128)}}" alt="User Image" class="w-20 h-20 rounded-full mr-4 shadow-lg">
        {% endif %}
        <div>
          <h3 class="text-xl font-semibold">{{ report.user.username}}</h3>
        </div>
      </div>
    </div>

    <!-- Report Images -->
    <div class="bg-gradient-to-r from-green-400 to-green-500 rounded-lg p-6 text-white mb-8">
      <h2 class="text-2xl font-semibold mb-4">Report Images</h2>
      <div class="grid grid-cols-2 md:grid-cols-2 gap-4">
        {% for image in report_images %}
        <img src="{{ url_for('static', filename='images/reports/' + report.reportId | string + '/' + image) }}" alt="Report Image {{ loop.index }}" class="rounded-lg shadow-lg">
        {% endfor %}
      </div>
    </div>

    <!-- Map Section -->
    <div class="bg-gradient-to-r from-green-400 to-green-500 rounded-lg p-6 text-white mb-8">
      <h2 class="text-2xl font-semibold mb-4">Report Location</h2>
      <div id="map" style="height: 400px;"></div>
      <script>
        // Initialize the map
        var map = L.map('map').setView([{{ report.latitude }}, {{ report.longitude }}], 15);

        // Add a tile layer (OpenStreetMap)
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                }).addTo(map);

        // Add a marker for the report location
        L.marker([{{ report.latitude }}, {{ report.longitude }}]).addTo(map)
          .bindPopup("Report Location: {{ report.locationAddress }}")
          .openPopup();
      </script>
    </div>

    {% if report.comments %}
    <!-- Comments Section -->
    <div id="comments" class="bg-gradient-to-r from-red-400 to-red-500 rounded-lg p-6 text-white mb-8">
      <h2 class="text-2xl font-semibold mb-4">Comments</h2>
      <div class="space-y-4">
        {% for comment in report.comments %}
        <div class="bg-gray-200 p-4 rounded-lg">
          <p class="text-gray-600"><strong>@{{ comment.user.username }}</strong> {{ comment.content }}</p>
          <p class="text-gray-400">Posted on {{ moment(comment.dateCreated).format('LLLL') }}</p>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}

    {% if report.reportAssignments %}
    {% set assignment = report.reportAssignments[-1] %}

    {% if assignment.reportResolution %}
    {% set resolution = assignment.reportResolution %}

    <div class="bg-gradient-to-r from-green-400 to-green-500 rounded-lg p-6 text-white mb-8">
      <div>
        <h2 class="text-2xl font-semibold mb-2">Report Resolution Details</h2>
        <div class="my-4">
          <h3 class="text-2xl font-semibold mb-2">Severity Level</h3>
          <p>{{ resolution.severityLevel }}</p>
        </div>
      </div>
      <div class="my-4">
        <h3 class="text-2xl font-semibold mb-2">Date Completed</h3>
        <p>{{ moment(resolution.dateCompleted).format('LLL') }}</p>
      </div>
      <div class="my-4">
        <h3 class="text-2xl font-semibold mb-2">Initial Situation</h3>
        <p>{{ resolution.initialSituationDescription }}</p>
      </div>
      <div class="my-4">
        <h3 class="text-2xl font-semibold mb-2">Steps Taken</h3>
        <p>{{ resolution.stepsTaken }}</p>
      </div>
      <div class="my-4">
        <h3 class="text-2xl font-semibold mb-2">Recommendations</h3>
        <p>{{ resolution.recommendations }}</p>
      </div>
      <div class="my-4">
        <h3 class="text-2xl font-semibold mb-2">Potential Causes</h3>
        <p>{{ resolution.potentialCauses }}</p>
      </div>
      <div class="my-4">
        <h3 class="text-2xl font-semibold mb-2">Man Power Utilized</h3>
        <p>{{ resolution.manPowerDetails }}</p>
      </div>
      <div class="my-4">
        <h3 class="text-2xl font-semibold mb-2">Financial Costs</h3>
        <p>{{ resolution.financialCosts }}</p>
      </div>
    </div>
</div>
{% else %}
{% if assignment.handler == current_user %}
<h2 class="text-2xl font-semibold mb-4">Attach Resolution Instance</h2>
<form method="POST" enctype="multipart/form-data" action="">
  <div class="mt-6">
    <label class="block text-sm font-semibold mb-2">Select resolution instance</label>
    {{ form.reportResolutionId(class="w-full px-4 py-2 border rounded-lg focus:ring focus:ring-blue-300") }}
    {% for error in form.reportResolutionId.errors %}
    <p class="text-red-500">{{ error }}</p>
    {% endfor %}
  </div>
  <div class="mt-6">
    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-lg">Submit</button>
  </div>
</form>
{% endif %}
{% endif %}
{% endif %}
</div>
{% endblock content %}